package com.ruoyi.api.controller;

import com.ruoyi.api.service.IDatasourceService;
import com.ruoyi.common.core.controller.BaseController;
import io.swagger.annotations.Api;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * 数据源Controller
 *
 * @author wei
 * @date 2022-08-22
 */
@Api(tags="数据源模块")
@RestController
@RequestMapping("/examing")
@RequiredArgsConstructor
public class DatasourceController1 extends BaseController {

    private final IDatasourceService datasourceService;

    /**
     * 查询数据源列表
     */
    @GetMapping("/answer.do")
    public String list() {
        //return "{\"o_errortext\":\"\",\"o_remainingtime\":38,\"o_capimageflag\":0,\"o_errorcode\":0,\"questanswer\":\"<table width='100%' border='0' cellspacing='0' cellpadding='0' class='ks_st'>\\r\\n\\r\\n  \\r\\n  <tr><td class=\\\"ks_ti_02\\\" colspan=\\\"2\\\" style=\\\"height:16px;\\\">单选题<\\/td><\\/tr>\\r\\n  <tr>\\r\\n    <td class='head'>\\r\\n      <!-- 当前题号 、当前题号考生答案 -->\\r\\n      <input name='dqth' id='dqth' type='hidden' value='13'\\/>\\r\\n      <span class='red'>13 <\\/span>\\r\\n      <span id='ksda' style='DISPLAY: none'><\\/span>\\r\\n      扑救贵重设备、档案资料、仪器仪表、600V以下的电器及油脂等火灾，用（  ）。\\r\\n      <span class='blue'>\\r\\n                  <img src='.\\/images\\/grayflagl.gif' onclick='mycheck(this);' title='重点检查' id='check' name='check' \\/>\\r\\n              <\\/span>\\r\\n    <\\/td><\\/tr>\\r\\n  <label id=\\\"stxx\\\">\\r\\n\\r\\n    \\r\\n      \\r\\n      <tr id=\\\"opstr\\\" onClick=\\\"selectRow(this, 13)\\\"\\r\\n        onMouseMove=\\\"moveColor(this);\\\" onMouseOut=\\\"outColor(this);\\\">\\r\\n                  <td class='article'>\\r\\n            <input onclick=\\\"setcheck(this)\\\" type='radio' name='option' value=\\\"A\\\" id=\\\"A\\\"\\r\\n               \\/>\\r\\n            A、二氧化碳灭火器\\r\\n          <\\/td>\\r\\n              <\\/tr>\\r\\n    \\r\\n      \\r\\n      <tr id=\\\"opstr\\\" onClick=\\\"selectRow(this, 13)\\\"\\r\\n        onMouseMove=\\\"moveColor(this);\\\" onMouseOut=\\\"outColor(this);\\\">\\r\\n                  <td class='article'>\\r\\n            <input onclick=\\\"setcheck(this)\\\" type='radio' name='option' value=\\\"B\\\" id=\\\"B\\\"\\r\\n               \\/>\\r\\n            B、泡沫灭火器\\r\\n          <\\/td>\\r\\n              <\\/tr>\\r\\n    \\r\\n      \\r\\n      <tr id=\\\"opstr\\\" onClick=\\\"selectRow(this, 13)\\\"\\r\\n        onMouseMove=\\\"moveColor(this);\\\" onMouseOut=\\\"outColor(this);\\\">\\r\\n                  <td class='article'>\\r\\n            <input onclick=\\\"setcheck(this)\\\" type='radio' name='option' value=\\\"C\\\" id=\\\"C\\\"\\r\\n               \\/>\\r\\n            C、酸碱灭火器\\r\\n          <\\/td>\\r\\n              <\\/tr>\\r\\n      <\\/label>\\r\\n<\\/table>\"}";
        //return "{\"o_errortext\":\"\",\"o_remainingtime\":57,\"o_capimageflag\":0,\"o_errorcode\":0,\"questanswer\":\"<table width='100%' border='0' cellspacing='0' cellpadding='0' class='ks_st'>\\r\\n\\r\\n  \\r\\n  <tr><td class=\\\"ks_ti_02\\\" colspan=\\\"2\\\" style=\\\"height:16px;\\\">多选题<\\/td><\\/tr>\\r\\n  <tr>\\r\\n    <td class='head'>\\r\\n      <!-- 当前题号 、当前题号考生答案 -->\\r\\n      <input name='dqth' id='dqth' type='hidden' value='4'\\/>\\r\\n      <span class='red'>4 <\\/span>\\r\\n      <span id='ksda' style='DISPLAY: none'><\\/span>\\r\\n      起重机上采用的有 （  ） 缓冲器。\\r\\n      <span class='blue'>\\r\\n                  <img src='.\\/images\\/grayflagl.gif' onclick='mycheck(this);' title='重点检查' id='check' name='check' \\/>\\r\\n              <\\/span>\\r\\n    <\\/td><\\/tr>\\r\\n  <label id=\\\"stxx\\\">\\r\\n\\r\\n    \\r\\n      \\r\\n      <tr id=\\\"opstr\\\" onClick=\\\"selectRow(this, 4)\\\"\\r\\n        onMouseMove=\\\"moveColor(this);\\\" onMouseOut=\\\"outColor(this);\\\">\\r\\n                  <td class='article'>\\r\\n            <input onclick=\\\"setcheck(this)\\\" type='checkbox' name='option' value=\\\"A\\\" id=\\\"A\\\"\\r\\n               \\/>\\r\\n            A、橡胶\\r\\n          <\\/td>\\r\\n              <\\/tr>\\r\\n    \\r\\n      \\r\\n      <tr id=\\\"opstr\\\" onClick=\\\"selectRow(this, 4)\\\"\\r\\n        onMouseMove=\\\"moveColor(this);\\\" onMouseOut=\\\"outColor(this);\\\">\\r\\n                  <td class='article'>\\r\\n            <input onclick=\\\"setcheck(this)\\\" type='checkbox' name='option' value=\\\"B\\\" id=\\\"B\\\"\\r\\n               \\/>\\r\\n            B、聚氨脂\\r\\n          <\\/td>\\r\\n              <\\/tr>\\r\\n    \\r\\n      \\r\\n      <tr id=\\\"opstr\\\" onClick=\\\"selectRow(this, 4)\\\"\\r\\n        onMouseMove=\\\"moveColor(this);\\\" onMouseOut=\\\"outColor(this);\\\">\\r\\n                  <td class='article'>\\r\\n            <input onclick=\\\"setcheck(this)\\\" type='checkbox' name='option' value=\\\"C\\\" id=\\\"C\\\"\\r\\n               \\/>\\r\\n            C、弹簧\\r\\n          <\\/td>\\r\\n              <\\/tr>\\r\\n    \\r\\n      \\r\\n      <tr id=\\\"opstr\\\" onClick=\\\"selectRow(this, 4)\\\"\\r\\n        onMouseMove=\\\"moveColor(this);\\\" onMouseOut=\\\"outColor(this);\\\">\\r\\n                  <td class='article'>\\r\\n            <input onclick=\\\"setcheck(this)\\\" type='checkbox' name='option' value=\\\"D\\\" id=\\\"D\\\"\\r\\n               \\/>\\r\\n            D、液压\\r\\n          <\\/td>\\r\\n              <\\/tr>\\r\\n      <\\/label>\\r\\n<\\/table>\"}";
        return "{\"o_errortext\":\"\",\"o_remainingtime\":57,\"o_capimageflag\":0,\"o_errorcode\":0,\"questanswer\":\"<table width='100%' border='0' cellspacing='0' cellpadding='0' class='ks_st'>\\r\\n\\r\\n  \\r\\n  <tr><td class=\\\"ks_ti_02\\\" colspan=\\\"2\\\" style=\\\"height:16px;\\\">判断题<\\/td><\\/tr>\\r\\n  <tr>\\r\\n    <td class='head'>\\r\\n      <!-- 当前题号 、当前题号考生答案 -->\\r\\n      <input name='dqth' id='dqth' type='hidden' value='4'\\/>\\r\\n      <span class='red'>4 <\\/span>\\r\\n      <span id='ksda' style='DISPLAY: none'><\\/span>\\r\\n      ()吊索的安全系数,无弯曲吊装K=6。\\r\\n      <span class='blue'>\\r\\n                  <img src='.\\/images\\/grayflagl.gif' onclick='mycheck(this);' title='重点检查' id='check' name='check' \\/>\\r\\n              <\\/span>\\r\\n    <\\/td><\\/tr>\\r\\n  <label id=\\\"stxx\\\">\\r\\n\\r\\n    \\r\\n      \\r\\n      <tr id=\\\"opstr\\\" onClick=\\\"selectRow(this, 4)\\\"\\r\\n        onMouseMove=\\\"moveColor(this);\\\" onMouseOut=\\\"outColor(this);\\\">\\r\\n                  <td class='article'>\\r\\n            <input onclick=\\\"setcheck(this)\\\" type='checkbox' name='option' value=\\\"A\\\" id=\\\"A\\\"\\r\\n               \\/>\\r\\n            A、正确\\r\\n          <\\/td>\\r\\n              <\\/tr>\\r\\n    \\r\\n      \\r\\n      <tr id=\\\"opstr\\\" onClick=\\\"selectRow(this, 4)\\\"\\r\\n        onMouseMove=\\\"moveColor(this);\\\" onMouseOut=\\\"outColor(this);\\\">\\r\\n                  <td class='article'>\\r\\n            <input onclick=\\\"setcheck(this)\\\" type='checkbox' name='option' value=\\\"B\\\" id=\\\"B\\\"\\r\\n               \\/>\\r\\n            B、错误\\r\\n          <\\/td>\\r\\n              <\\/tr>\\r\\n    \\r\\n      \\r\\n      <tr id=\\\"opstr\\\" onClick=\\\"selectRow(this, 4)\\\"\\r\\n        onMouseMove=\\\"moveColor(this);\\\" onMouseOut=\\\"outColor(this);\\\">\\r\\n                  <td class='article'>\\r\\n            <input onclick=\\\"setcheck(this)\\\" type='checkbox' name='option' value=\\\"C\\\" id=\\\"C\\\"\\r\\n               \\/>\\r\\n            C、弹簧\\r\\n          <\\/td>\\r\\n              <\\/tr>\\r\\n    \\r\\n      \\r\\n      <tr id=\\\"opstr\\\" onClick=\\\"selectRow(this, 4)\\\"\\r\\n        onMouseMove=\\\"moveColor(this);\\\" onMouseOut=\\\"outColor(this);\\\">\\r\\n                  <td class='article'>\\r\\n            <input onclick=\\\"setcheck(this)\\\" type='checkbox' name='option' value=\\\"D\\\" id=\\\"D\\\"\\r\\n               \\/>\\r\\n            D、液压\\r\\n          <\\/td>\\r\\n              <\\/tr>\\r\\n      <\\/label>\\r\\n<\\/table>\"}";
    }
}
